
//alert("Error! Please enter a valid password.");
//alert("Welcome to JS Land \n Happy Coding");
//alert("Welcome to JS Land");
//alert("Happy Coding");
//alert("Hello.. I can run JS through my web browser's console");
//var a, b, c;
//var one, One, one_1, _$dollor, _1$;
//var 1num, #num, num&, o ne, 1_num/; 
//alert("Rules for naming JS variables \n Variable names can only contain numbers, $ and _. For example : $my_1stVariable ");
//var age = 24;
//alert('I am '+ age + ' years old');
//var n = 14;
//alert("you have visited "+ n + " times");
//var birth = 1993;
//alert("My birth year is " + birth + "\ndata type of my variable is number"); 
//var name = prompt ("What is your name");
//var product_name = prompt ("Select your product");
//var qty = prompt ("How many products do you want");
//alert(name + " ordered " + q);
//var userName;
//var myName = "Muhammed Umer";
//var message;
//message = "Hello World";
//alert(message);
//alert("Umer");
//alert("15 years old");
//alert("certified Mobile Application Development");
//var email = "umer_1309e@aptechgdn.com";
//alert("My email address is " + email);
//var book = "A smarter way to learn JavaScript";
//alert("I am trying to learn from the Book " + book);
//document.write("Yah! I can write HTML content through Javascript");
//alert("PIZZA \nPIZZ \nPIZ \nPI \np");
//var _text = "“▬▬▬▬▬▬▬▬▬ஜ ۩۞۩ ஜ▬▬▬▬▬▬▬▬▬”";
//alert(_text);
//var num = 3 + 5;
//alert("Sum of 3 and 5 is " + num);
//var sub = 8 - 3;
//var product = 3 * 8;
//var div = 8 / 3;
//var mod = 8 % 3;
//alert ("Subtraction of 8 from 3 is " + sub +
        //"\nproduct of 3 and 8 is " + product + 
        //"\nDivision of 8 and 3 is " + div + 
        //"\nModulus of 8 and 3 is " + mod);
        //var num = 10;
        //document.write("value of nume is " + num);
        //var a = 5;
        //a++;
       // document.write("value after increament is: " + a );
       //a = a + 7;
       // document.write("value after addition is " + a);
       // a--;
      //  document.write("value after decreament is " + a);
      //a = a % 3;
      //document.write("The remainder is :" + a);
 // var ticket_cost = 600;
   //   var numOfTickets = prompt("Enter number of tickets", "0");
     // var total_price = ticket_cost * numOfTickets;
      //document.write("Total cost to buy 5 ticket to a movie is " + total_price + "pkr");
       // var num = 4;
    // document.write("Table of 4 <br>");
        // document.write(num + "x" + "1 =" + num * 1);
    //     document.write("<br>" + num + "x" + "2 = " + num * 2);
        // document.write("<br>" + num + "x" + "3 = " + num * 3);
        // document.write("<br>" + num + "x" + "4 = " + num * 4);
        // document.write("<br>" + num + "x" + "5 = " + num * 5);
        // document.write("<br>" + num + "x" + "6 = " + num * 6);
        // document.write("<br>" + num + "x" + "7 = " + num * 7);
        // document.write("<br>" + num + "x" + "8 = " + num * 8);
        // document.write("<br>" + num + "x" + "9 = " + num * 9);
        // document.write("<br>" + num + "x" + "10  =" + num * 10);
        //simple program of converting celcius into farenheit and farenheit into celcius
        // var cel_temp = prompt("Enter temperature in celcius");
        // var far_temp = prompt("Enter temperature in farhenite");
        // var c = (far_temp - 32) * 5 / 9;
        // var f = (cel_temp / 5) + 32;
        // document.write(cel_temp + "<sup>o</sup>C "+  "is " + f + "<sup>o</sup>F");
        // document.write("<br>" + far_temp + "<sup>o</sup>F " + "is " + c + "<sup>o</sup>C");
        //Shopping cart
        // var item_1Price = 600;
        // var qty_Item1 = prompt("number of orders");
        // var item_2Price = 500;
        // var qty_Item2 = prompt("number of orders");
        // var shipCharges = 200;
        // var total_cost = (item_1Price * qty_Item1) + (item_2Price * qty_Item2) + shipCharges;
        // document.write("<br>Price of item 1 is " + item_1Price);
        // document.write("<br>Quantity of item 1 is " + qty_Item1);
        // document.write("<br>Price of item 2 is " + item_2Price);
        // document.write("<br>Quantity of item 2 is " + qty_Item2);

        // document.write("<br>Total Cost of your order is " + total_cost);
        //  var eng = prompt("Enter English marks");
        //  var math = prompt("Enter math marks");
        //  var urdu = prompt ("Enter urdu marks");
        //  var eng1 = parseInt(eng);
        //  var math1 = parseInt(math);
        //  var urdu1 = parseInt(urdu);
        //  var obt_marks = (eng1 + math1 + urdu1);
        //  var total_marks = 300;
        //  var per = (obt_marks / total_marks) * 100;
        //  document.write("<br>Total Marks = " + total_marks);
        //  document.write("<br>obtain marks = " + obt_marks);
        //  document.write("<br>Percentage = " + per + "%");
            // var sauRial = 25;
            // var usDollor = 10;
            // var total = (sauRial * 28) + (usDollor * 104.80);
            // document.write("<h1>Currency in PKR</h1> ");
            // document.write("<br>total Currency in PKR</h1>" + total);
           //age calculator
            // var currYear = prompt("Current year");
            // var birthYear = prompt("write the birth year ");
            // var age = currYear - birthYear;
            // document.write("Current Year" + currYear);
            // document.write("<br>Birth Year" + currYear);
            // document.write("<br>Your age is " + age);
